[audio]
buffer_size = 1024
channels = 1
max_duration = 600.0
mute_other_apps = false
sample_rate = 16000
silence_duration = 0.30000001192092896
vad_enabled = true
vad_threshold = 0.5

[daemon]
log_level = 'info'
pid_file = '/tmp/autowhisper.pid'
work_dir = '/opt/autowhisper'

[feedback]
duration = 0.10000000149011612
enabled = true
frequency_error = 600
frequency_start = 800
frequency_stop = 400
volume = 0.30000001192092896

[hotkeys]
cancel = [ 'esc' ]
escape_to_cancel = true
mode = 'push_to_talk'
trigger = [ 'shift+super' ]

[model]
beam_size = 1
compute_type = 'bfloat16'
device = 'cuda'
language = 'en'
num_threads = 4
size = 'distil-small.en'

[output]
also_copy_to_clipboard = true
auto_paste = true
ending_action = 'none'
lowercase = false
method = 'inject'
paste_delay = 0.05000000074505806

[tray]
enabled = true